//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher
    {
        public int Id { get; set; }
        public string PublisherName { get; set; }
        public int BookId { get; set; }
        public int CountryId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Country Country { get; set; }
    }
}
